using System.Collections.Generic;

namespace Griffin.Wiki.Core.Services
{
    /// <summary>
    /// Result generated by the Wiki parser.
    /// </summary>
    public interface IWikiParserResult
    {
        /// <summary>
        /// Gets all wiki pages that the body links to
        /// </summary>
        IEnumerable<string> PageLinks { get; }

        /// <summary>
        /// Gets generated content/body.
        /// </summary>
        string Content { get; }
    }
}